name: Check Task Status

on:
  push:
    branches:
      - main

jobs:
  check_task:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Task Status
      run: |
        task_status=$(cat task_status.txt)

        if [ "$task_status" == "pending" ]; then
          echo "Task is still pending."
          exit 1  # Exit with a non-zero status to indicate a failure.
        elif [ "$task_status" == "finished" ]; then
          echo "Task is finished."
        else
          echo "Invalid task status."
          exit 1  # Exit with a non-zero status for any unexpected status.
        fi
