name: Auto Merge On Test Success

on:
  push:
    branches:
      - main  # Change to the default branch of your repository

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change to your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # Modify as per your project setup

    - name: Run Tests
      run: pytest  # Replace with your test command

  merge:
    runs-on: windows-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge if Tests Passed
      run: |
        # Check if the 'test' job was successful
        if [[ "${{ needs.test.result }}" == "success" ]]; then
          # If tests passed, merge the changes
          git fetch
          git merge --ff-only ${{ github.ref }}
          git push
        else
          echo "Tests failed, not merging changes."
        fi
